"""Convert report/PreThesis_Report.md to a compilable LaTeX document.

Generated rather than hand-written, for the same reason `build_docx.py` is: the
Markdown is the single source of truth, every number in it came from a script,
and a hand-maintained second copy would drift away from both.

Compile with **XeLaTeX** or **LuaLaTeX**, not pdfLaTeX. The report contains
Vietnamese verbatim quotations (Appendix C), Greek letters (κ, θ, Δ) and typographic
dashes, all of which need a Unicode engine and a font with the coverage.
Overleaf: Menu → Compiler → XeLaTeX.

Usage:
    python report/build_latex.py [--out report/PreThesis_Report.tex]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPORT_DIR = Path(__file__).resolve().parent
SOURCE = REPORT_DIR / "PreThesis_Report.md"
TARGET = REPORT_DIR / "PreThesis_Report.tex"

# Front-matter headings that are their own unnumbered chapters.
FRONT_MATTER = {
    "ACKNOWLEDGMENTS",
    "ABSTRACT",
    "TABLE OF CONTENTS",
    "LIST OF FIGURES",
    "LIST OF TABLES",
    "REFERENCES",
}

PREAMBLE = r"""% !TEX program = xelatex
%
% Generated by report/build_latex.py from report/PreThesis_Report.md.
% Do not edit by hand: regenerate instead, or the .tex and the .md diverge.
%
% OVERLEAF: set Menu -> Compiler -> XeLaTeX before compiling. pdfLaTeX cannot
% typeset the Vietnamese quotations in Appendix C. The magic comment on line 1
% asks Overleaf to do this automatically, but set it manually if it does not.
%
% Times New Roman is not installed on Overleaf, so the document falls back to
% TeX Gyre Termes, which is metrically compatible and covers Vietnamese. On a
% local machine that has Times New Roman it will use that instead, matching the
% faculty template.

\documentclass[a4paper,13pt,oneside]{report}

\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{english}
% Vietnamese is deliberately NOT declared as another polyglossia language. The
% document never switches language environments, the quotations are short, and
% the Unicode font already carries the diacritics; loading a gloss that a given
% TeX Live release might lack would add a failure mode for no typographic gain.

\IfFontExistsTF{Times New Roman}{
  \setmainfont{Times New Roman}
}{
  \IfFontExistsTF{TeX Gyre Termes}{\setmainfont{TeX Gyre Termes}}{\setmainfont{Latin Modern Roman}}
}
\IfFontExistsTF{Consolas}{
  \setmonofont{Consolas}[Scale=0.85]
}{
  \setmonofont{Latin Modern Mono}[Scale=0.9]
}

\usepackage[a4paper,top=2.5cm,bottom=2.5cm,left=3cm,right=2.5cm]{geometry}
\usepackage{setspace}
\onehalfspacing

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{array}
\usepackage{ragged2e}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{enumitem}
\usepackage{fancyvrb}
\usepackage[hidelinks,unicode]{hyperref}
\usepackage{titlesec}
\usepackage{fancyhdr}

% Wrapping columns for the wide comparison tables.
\newcolumntype{L}[1]{>{\RaggedRight\arraybackslash}p{#1}}

\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}
\setlist{nosep,topsep=4pt}

\titleformat{\chapter}[display]
  {\normalfont\Large\bfseries}{\chaptertitlename\ \thechapter}{10pt}{\LARGE}
\titlespacing*{\chapter}{0pt}{-20pt}{20pt}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0pt}

% Callout used for the report's blockquote notes.
\newenvironment{calloutbox}
  {\begin{quote}\itshape\small}
  {\end{quote}}

\begin{document}
"""

TITLE_BLOCK = r"""
\begin{titlepage}
\centering
\vspace*{1cm}

{\large VIETNAM NATIONAL UNIVERSITY OF HO CHI MINH CITY\par}
{\large THE INTERNATIONAL UNIVERSITY\par}
{\large SCHOOL OF COMPUTER SCIENCE AND ENGINEERING\par}

\vspace{3cm}

{\LARGE\bfseries An LLM-powered Application for Detecting\\[0.3em]
Stress Levels in Vietnamese University Students\par}

\vspace{2cm}

{\large PRE-THESIS REPORT\par}

\vfill

\begin{tabular}{rl}
Student: & \rule{5cm}{0.4pt} \\[0.8em]
Student ID: & \rule{5cm}{0.4pt} \\[0.8em]
Supervisor: & \rule{5cm}{0.4pt} \\
\end{tabular}

\vspace{2cm}
{\large \today\par}
\end{titlepage}

\tableofcontents
\clearpage
"""


# ---------------------------------------------------------------------------
# Escaping
# ---------------------------------------------------------------------------

# Order matters: the backslash must be replaced first.
_ESCAPES = [
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
]

# Characters the body fonts do not cover. Overleaf has no Microsoft fonts, so the
# document falls back to TeX Gyre Termes, which carries Latin and Vietnamese but
# not dingbats or emoji. Left alone these vanish silently with only a "Missing
# character" warning in the log, which is the worst kind of failure: the PDF
# looks finished and a tick column is simply blank.
_GLYPHS = {
    "✓": r"\checkmark{}",
    "✔": r"\checkmark{}",
    "✗": r"$\times$",
    "✘": r"$\times$",
    "→": r"$\rightarrow$",
    "←": r"$\leftarrow$",
    "≥": r"$\geq$",
    "≤": r"$\leq$",
    "≈": r"$\approx$",
    "×": r"$\times$",
    "·": r"\textperiodcentered{}",
    "⁻": r"\textsuperscript{-}",
    "⁵": r"\textsuperscript{5}",
    "θ": r"$\theta$",
    "κ": r"$\kappa$",
    "α": r"$\alpha$",
    "Δ": r"$\Delta$",
    "σ": r"$\sigma$",
    "ϑ": r"$\vartheta$",
    "λ": r"$\lambda$",
    "β": r"$\beta$",
    "η": r"$\eta$",
    "ε": r"$\epsilon$",
    "ℓ": r"$\ell$",
}

# Emoji carry no typographic meaning here and have no glyph in any body font.
# Stripping them is honest; substituting a lookalike would misrepresent the
# deployed string that the appendix claims to reproduce verbatim.
#
# The ranges deliberately include U+1F100-U+1F1FF (enclosed alphanumerics, where
# 🆘 lives) and exclude nothing from the dingbat block, because _GLYPHS runs
# FIRST and has already converted the dingbats worth keeping. Stripping before
# mapping silently deleted every ✓ and ✗ in the document, leaving blank cells in
# the reverse-scoring and ablation tables.
_EMOJI = re.compile(
    "[\U0001F000-\U0001FAFF\U00002600-\U000027BF\U0000FE00-\U0000FE0F\U00002190-\U000021FF]"
)

# What a verbatim block gets instead: a LaTeX command there would print as
# literal source, so only plain-text stand-ins are available.
_VERBATIM_GLYPHS = {"✓": "[x]", "✗": "[ ]", "→": "->", "←": "<-", "≥": ">=", "≤": "<="}


def strip_unsupported(text: str, *, in_verbatim: bool = False) -> str:
    """Replace or remove characters the body font cannot render.

    Order matters: map the glyphs that have LaTeX equivalents before removing
    the rest, or the emoji ranges swallow the dingbats on the way past.
    """
    if in_verbatim:
        for ch, repl in _VERBATIM_GLYPHS.items():
            text = text.replace(ch, repl)
        return _EMOJI.sub("", text)

    for ch, repl in _GLYPHS.items():
        text = text.replace(ch, repl)
    return _EMOJI.sub("", text)


def escape(text: str) -> str:
    """Escape LaTeX specials in plain prose."""
    for old, new in _ESCAPES:
        text = text.replace(old, new)
    return text


def inline(text: str) -> str:
    """Convert Markdown inline markup to LaTeX, escaping everything else.

    Code spans and maths are extracted before escaping and restored afterwards,
    because their contents must not be escaped as prose: `$\\theta$` is maths and
    `` `--limit` `` is verbatim.
    """
    placeholders: list[str] = []

    def stash(value: str) -> str:
        placeholders.append(value)
        return f"\x00{len(placeholders) - 1}\x00"

    # Raw HTML the Markdown used for spacing has no LaTeX meaning and would
    # otherwise be typeset literally as "<br>".
    text = re.sub(r"</?br\s*/?>", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"</?(?:sub|sup|b|i|em|strong|u|span|div)\b[^>]*>", "", text, flags=re.IGNORECASE)

    # Inline maths first: it is already LaTeX.
    text = re.sub(r"\$([^$]+)\$", lambda m: stash(f"${m.group(1)}$"), text)
    # Code spans.
    text = re.sub(
        r"`([^`]+)`",
        lambda m: stash(r"\texttt{" + escape(strip_unsupported(m.group(1))) + "}"),
        text,
    )
    # Links: keep the label, drop the target (they are repo-relative paths).
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", text)

    text = escape(text)

    # Emphasis, after escaping so the markers survive.
    text = re.sub(r"\*\*([^*]+)\*\*", r"\\textbf{\1}", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"\\textit{\1}", text)

    text = strip_unsupported(text)

    for i, value in enumerate(placeholders):
        text = text.replace(f"\x00{i}\x00", value)
    return text


# ---------------------------------------------------------------------------
# Block conversion
# ---------------------------------------------------------------------------


def convert_table(rows: list[str]) -> str:
    """Pipe table to a longtable, so wide tables break across pages."""
    def cells(line: str) -> list[str]:
        # Split on unescaped pipes only. A cell may legitimately contain `\|`,
        # as the technology table does for `prompt \| llm \| parser`; splitting
        # on that too shredded the row into the wrong number of columns and
        # produced a mangled cell in the output.
        parts = re.split(r"(?<!\\)\|", line.strip().strip("|"))
        return [c.strip().replace(r"\|", "|") for c in parts]

    header = cells(rows[0])
    body = [cells(r) for r in rows[2:] if r.strip()]
    n = len(header)

    # Narrow numeric tables get centred columns; anything wider wraps.
    widths = [max((len(r[i]) for r in [header] + body if i < len(r)), default=0) for i in range(n)]
    spec = "".join("l" if w <= 14 else f"L{{{min(5.5, 2.2 + w / 22):.1f}cm}}" for w in widths)

    out = [r"\begin{longtable}{" + spec + "}", r"\toprule"]
    out.append(" & ".join(rf"\textbf{{{inline(h)}}}" for h in header) + r" \\")
    out += [r"\midrule", r"\endhead"]
    for row in body:
        row = (row + [""] * n)[:n]
        out.append(" & ".join(inline(c) for c in row) + r" \\")
    out += [r"\bottomrule", r"\end{longtable}", ""]
    return "\n".join(out)


def convert(md: str) -> str:
    lines = md.split("\n")
    out: list[str] = []
    i = 0
    seen_title = False
    # Mutable latch so the nested heading branch can set it.
    emitted_appendix = [False]

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # --- fenced code -------------------------------------------------
        if stripped.startswith("```"):
            lang = stripped[3:].strip().lower()
            i += 1
            block: list[str] = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1
            if lang == "mermaid":
                # Diagrams cannot be typeset here; point at the source instead of
                # dropping them silently, so a reader knows something exists.
                out += [
                    r"\begin{calloutbox}",
                    "Diagram omitted from the LaTeX build (Mermaid source). "
                    "See the corresponding figure in the Markdown report.",
                    r"\end{calloutbox}",
                    "",
                ]
            else:
                out += [r"\begin{Verbatim}[fontsize=\small,breaklines=true]"]
                out += [strip_unsupported(b, in_verbatim=True) for b in block]
                out += [r"\end{Verbatim}", ""]
            continue

        # --- tables --------------------------------------------------------
        if stripped.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:|-]+\|?$", lines[i + 1].strip()):
            table: list[str] = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                table.append(lines[i])
                i += 1
            out.append(convert_table(table))
            continue

        # --- headings ------------------------------------------------------
        heading = re.match(r"^(#{1,4})\s+(.*)$", stripped)
        if heading:
            level, title = len(heading.group(1)), heading.group(2).strip()
            i += 1

            # The three institution lines plus the title line become the title page.
            if not seen_title:
                if title.startswith(("VIETNAM NATIONAL", "THE INTERNATIONAL", "SCHOOL OF")):
                    continue
                if title.startswith("An LLM-powered"):
                    out.append(TITLE_BLOCK)
                    seen_title = True
                    continue

            plain = re.sub(r"^CHAPTER\s+\d+\s*[—-]\s*", "", title)

            # `\appendix` restarts chapter numbering as A, B, C. Emitted once,
            # before the first appendix, so the appendices stop being numbered
            # as Chapters 7-10 and the heading stops repeating its own letter.
            appendix = re.match(r"^APPENDIX\s+([A-Z])\s*[—-]\s*(.*)$", plain)
            if appendix and not emitted_appendix[0]:
                out.append(r"\appendix")
                emitted_appendix[0] = True
            if appendix:
                plain = appendix.group(2)

            # Strip a leading section number: LaTeX numbers headings itself, so
            # "1.1 Background" under \chapter{INTRODUCTION} would otherwise be
            # typeset as "1.1  1.1 Background".
            plain = re.sub(r"^(?:[A-D]|\d+)\.\d+(?:\.\d+)?\s+", "", plain)

            if title.upper() in FRONT_MATTER or any(title.upper().startswith(f) for f in FRONT_MATTER):
                # The generated ToC replaces the authored one.
                if title.upper().startswith("TABLE OF CONTENTS"):
                    while i < len(lines) and not re.match(r"^#{1,4}\s", lines[i].strip()):
                        i += 1
                    continue
                out.append(rf"\chapter*{{{inline(plain)}}}")
                out.append(rf"\addcontentsline{{toc}}{{chapter}}{{{inline(plain)}}}")
            elif level == 1:
                out.append(rf"\chapter{{{inline(plain)}}}")
            elif level == 2:
                out.append(rf"\section{{{inline(plain)}}}")
            elif level == 3:
                out.append(rf"\subsection{{{inline(plain)}}}")
            else:
                out.append(rf"\subsubsection{{{inline(plain)}}}")
            out.append("")
            continue

        # --- display maths ---------------------------------------------------
        if stripped.startswith("$$"):
            # A single-line `$$ ... $$` closes on its own line. Missing that case
            # made the scanner run on to the next `$$` in the document, which
            # swallowed everything from §4.5 to the end of the report.
            if stripped.count("$$") >= 2:
                body = stripped.strip("$").strip()
                i += 1
            else:
                block: list[str] = []
                i += 1
                while i < len(lines) and "$$" not in lines[i]:
                    block.append(lines[i])
                    i += 1
                i += 1  # consume the closing fence
                body = "\n".join(block).strip()
            out += [r"\begin{equation*}", body, r"\end{equation*}", ""]
            continue

        # --- blockquote -------------------------------------------------------
        if stripped.startswith(">"):
            quote: list[str] = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quote.append(lines[i].strip().lstrip(">").strip())
                i += 1
            out += [r"\begin{calloutbox}", inline(" ".join(q for q in quote if q)), r"\end{calloutbox}", ""]
            continue

        # --- lists -------------------------------------------------------------
        bullet = re.match(r"^[-*]\s+(.*)$", stripped)
        number = re.match(r"^(\d+)\.\s+(.*)$", stripped)
        if bullet or number:
            ordered = bool(number)
            env = "enumerate" if ordered else "itemize"
            out.append(rf"\begin{{{env}}}")
            while i < len(lines):
                s = lines[i].strip()
                m = re.match(r"^(\d+)\.\s+(.*)$", s) if ordered else re.match(r"^[-*]\s+(.*)$", s)
                if m:
                    out.append(r"\item " + inline(m.group(2) if ordered else m.group(1)))
                    i += 1
                elif s and not re.match(r"^(#{1,4}\s|[-*]\s|\d+\.\s|\||>|```)", s):
                    # Continuation line of the current item.
                    out.append(inline(s))
                    i += 1
                elif not s:
                    # Blank lines separate items in this document. Look past them:
                    # if the list continues, stay in the same environment rather
                    # than closing and reopening it, which would restart at 1.
                    j = i
                    while j < len(lines) and not lines[j].strip():
                        j += 1
                    nxt = lines[j].strip() if j < len(lines) else ""
                    cont = re.match(r"^\d+\.\s", nxt) if ordered else re.match(r"^[-*]\s", nxt)
                    if cont:
                        i = j
                    else:
                        break
                else:
                    break
            out += [rf"\end{{{env}}}", ""]
            continue

        # --- page break marker --------------------------------------------------
        if stripped == r"\newpage":
            out += [r"\clearpage", ""]
            i += 1
            continue

        # --- horizontal rule ----------------------------------------------------
        if re.match(r"^-{3,}$", stripped):
            i += 1
            continue

        # --- plain paragraph -----------------------------------------------------
        if stripped:
            out.append(inline(stripped))
        else:
            out.append("")
        i += 1

    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=str(SOURCE))
    parser.add_argument("--out", default=str(TARGET))
    args = parser.parse_args()

    md = Path(args.source).read_text(encoding="utf-8")
    tex = PREAMBLE + convert(md) + "\n\\end{document}\n"

    target = Path(args.out)
    target.write_text(tex, encoding="utf-8")

    pages = len(tex) // 2600  # rough, at this font and spacing
    print(f"Wrote {target} ({len(tex):,} chars, ~{pages} pages)")
    print("Compile with XeLaTeX (Overleaf: Menu -> Compiler -> XeLaTeX).")


if __name__ == "__main__":
    main()
